services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service_app
    restart: always
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    expose:
      - "3630"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - global-network-geosandbox

  db:
    image: postgres:17
    container_name: user_service_db
    restart: always
    user: postgres
    secrets:
      - db-password
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_user_geosandbox
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "5434:5432"
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d db_user_geosandbox" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  default:
  global-network-geosandbox:
    name: global-network-geosandbox
