services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service_app
    restart: always
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    expose:
      - "3630"

networks:
    global-network-geosandbox:
      external: true